services:
  - type: web
    name: medicine-tracker-backend
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: singapore # You can change this to your preferred region (e.g., oregon, frankfurt, singapore, ohio)
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: RENDER_MONGO_URI
        value: mongodb+srv://dhanushpaladugu:Vaishu%2377@medicine.gbwuu3m.mongodb.net/medicine_tracker?appName=medicine
      - key: JWT_SECRET
        generateValue: true # Generates a secure random JWT secret automatically
      - key: FRONTEND_URL
        value: http://localhost:5173 # Update this to your frontend URL once deployed
      - key: ENABLE_EMAIL_NOTIFICATIONS
        value: "false"
      - key: MANAGEMENT_HEALTH_MAIL_ENABLED
        value: "false"
