spring:
  mongodb:
    uri: ${RENDER_MONGO_URI:${SPRING_DATA_MONGODB_URI:}}
    database: ${MONGO_DATABASE:medicine_tracker}
    uuid-representation: standard



management:
  health:
    mail:
      enabled: false
